name: grisette-synth-lib
version: 0.1.0.0
synopsis: Library for building synthesizers with Grisette
description: Library for building synthesizers with Grisette
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu, Rastislav Bodík"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-synth-lib
copyright: "2023-2024 Sirui Lu"
extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.14 && < 5
  - grisette >= 0.6 && < 0.7
  - mtl >= 2.2.2 && < 2.4
  - unordered-containers >= 0.2.11 && < 0.3
  - QuickCheck >= 2.14 && < 2.15
  - quickcheck-with-counterexamples >= 1.2 && < 1.3
  - sbv >= 8.11 && < 11
  - hashable >= 1.3 && < 1.5
  - text >= 1.2.4.1 && < 2.2
  - prettyprinter >= 1.5 && < 1.8
  - ordered-containers >= 0.2.3 && < 0.3
  - deepseq
  - graphviz >= 2999.20.0.4 && < 3000
  - extra
  - template-haskell
  - stm
  - containers
  - async
  - time

ghc-options:
  - -Wextra
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wpartial-fields
  - -Wunused-type-patterns

library:
  source-dirs: src

executables:
  arith:
    source-dirs: arith
    main: Main.hs
    dependencies: grisette-synth-lib
  control:
    source-dirs: control
    main: Main.hs
    dependencies: grisette-synth-lib

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette-synth-lib
      - test-framework >= 0.8.2 && < 0.9
      - test-framework-hunit >= 0.3.0.2 && < 0.4
      - test-framework-quickcheck2 >= 0.3.0.5 && < 0.4
      - HUnit >= 1.6
